image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
#  only:
#    - master

unit-test:
  image: python:3.9
  stage: test
  before_script:
    - pip install -r requirements.txt
    - apt-get update && apt-get install -y redis-server
    - redis-server --port 6379 --bind 127.0.0.1 &
  script:
    - python manage.py makemigrations user
    - python manage.py makemigrations chat
    - python manage.py makemigrations message
    - python manage.py migrate
    - chmod +x test.sh
    - ./test.sh
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner
#  only:
#    - master

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
#  only:
#    - master
